name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: ./Phase2_frontend
    - name: Install dependencies    
      working-directory: ./Phase2_frontend
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./Phase2_frontend
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      working-directory: ./Phase2_frontend
      run: npx playwright test --reporter=html
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./Phase2_frontend/playwright-report/
        retention-days: 30
    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ !cancelled() }}
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Phase2_frontend/playwright-report
        destination_dir: reports/${{ github.run_number }}
        keep_files: true
        enable_jekyll: false
        force_orphan: true
    - name: Send comprehensive report data to n8n
      if: ${{ !cancelled() }}
      run: |
        cd ./Phase2_frontend
        
        # Check if HTML report exists
        if [ ! -f "playwright-report/index.html" ]; then
          echo "HTML report not found, skipping n8n notification"
          exit 0
        fi
        
        # Extract test results summary from HTML report
        TEST_SUMMARY=$(grep -o '<div class="suites">.*</div>' playwright-report/index.html | head -1 || echo "Test summary not found")
        REPORT_SIZE=$(wc -c < playwright-report/index.html)
        
        # Create comprehensive report data with test results and metadata
        REPORT_DATA=$(jq -n \
          --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          --arg commit "${{ github.sha }}" \
          --arg run_id "${{ github.run_id }}" \
          --arg run_number "${{ github.run_number }}" \
          --arg pages_url "https://patilpriyadarshini.github.io/migration-repo/reports/${{ github.run_number }}/index.html" \
          --arg repository "${{ github.repository }}" \
          --arg test_summary "$TEST_SUMMARY" \
          --arg report_size "$REPORT_SIZE" \
          --arg workflow_status "completed" \
          '{
            timestamp: $timestamp,
            commit_sha: $commit,
            run_id: $run_id,
            run_number: $run_number,
            pages_url: $pages_url,
            repository: $repository,
            event_type: "playwright_report_published",
            test_summary_html: $test_summary,
            report_size_bytes: ($report_size | tonumber),
            workflow_status: $workflow_status,
            content_type: "text/html",
            message: "Playwright tests completed. Full HTML report available at GitHub Pages URL."
          }')
        
        # Send to n8n webhook with retry logic
        if [ -n "${{ secrets.N8N_WEBHOOK_URL }}" ]; then
          echo "Sending comprehensive report data to n8n webhook..."
          echo "Report size: $REPORT_SIZE bytes"
          echo "Pages URL: https://patilpriyadarshini.github.io/migration-repo/reports/${{ github.run_number }}/index.html"
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$REPORT_DATA" \
            "${{ secrets.N8N_WEBHOOK_URL }}" \
            --max-time 30 \
            --retry 3 \
            --retry-delay 5 \
            --fail-with-body || {
              echo "Webhook failed after retries, but continuing workflow..."
              echo "Webhook URL: ${{ secrets.N8N_WEBHOOK_URL }}"
              echo "Payload size: $(echo "$REPORT_DATA" | wc -c) bytes"
            }
        else
          echo "N8N_WEBHOOK_URL not configured, skipping webhook notification"
        fi
